Repository JNU-econovation/econo-recruit, pull requests merged in 2024-09, with the labels that each got.

#242 [FEATURE] 칸반보드 조회 시 기수 별로 조회
  .github/workflows/dev.yml
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/controller/BoardRestController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/service/CardService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/usecase/CardLoadUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/config/security/CorsConfig.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/config/security/ServletFilterConfiguration.java
  server/Recruit-Api/src/main/resources/application.yml
Labels: feature✨

#244 [FEATURE] 칸반보드 조회 시 기수 별로 조회
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/controller/BoardRestController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/service/CardService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/usecase/CardLoadUseCase.java
Labels: feature✨

#245 [REFACTOR] 칸반보드 기수별 조회 로직 수정
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/service/CardService.java
Labels: refactor♻️

#246 refactor: null 처리 Optional 형태로 변경
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/service/CardService.java
Labels: refactor♻️

#247 [REFACTOR] Optional 구문 수정 및 기본 board 는 true 반환
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/service/CardService.java
Labels: refactor♻️

#248 feature: Slack 알림 off시 Card 생성 Event 핸들러 추가
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/handler/ApplicantCardCreateEventHandler.java
Labels: enhancement

#249 [REFACTOR] 면접 기록 지원 기수별로 조회하도록 수정
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/controller/RecordController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/usecase/RecordUseCase.java
Labels: refactor♻️

#250 [BE-91] 칸반보드 API에서 year가 null일 경우 전체 조회 할 수 있도록 변경
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/controller/BoardRestController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/service/CardService.java
Labels: refactor♻️

#251 [FEATURE] 지원서 합/불 상태 필드 추가 및 칸반보드 조회 시 합/불 상태 필드 추가
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/service/CardService.java
  server/Recruit-Common/src/main/java/com/econovation/recruitcommon/consts/RecruitStatic.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/PassStates.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/card/dto/BoardCardResponseDto.java
Labels: feature✨

#252 [FEATURE] Spring StateMachine 의존성 추가
  server/Recruit-Api/build.gradle
Labels: feature✨

#253 [BE-87] 지원서 합/불 필드 수정 및 조회 로직 수정
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/aggregate/ApplicantStateUpdateEventListener.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/handler/ApplicantStateUpdateEventHandler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/AnswerCommandService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/state/config/ApplicantStateMachineConfig.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/state/support/PeriodCalculator.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/service/CardService.java
  server/Recruit-Api/src/main/resources/application.yml
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/ApplicantState.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/MongoAnswer.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/PassStates.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/ApplicantState.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/PassStates.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/PeriodStates.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/card/dto/BoardCardResponseDto.java
Labels: refactor♻️

#254 [REFACTOR] MongoAnswer state 필드 null 처리 및 PATCH 응답 형식 JSON으로 변경
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/aggregate/ApplicantStateUpdateEventListener.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/controller/ApplicantController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/handler/ApplicantStateUpdateEventHandler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/AnswerCommandService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/ApplicantService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/usecase/ApplicantCommandUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/service/CardService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/utils/ApplicantStateCheck.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/MongoAnswer.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/event/domainevent/ApplicantStateEvents.java
Labels: refactor♻️

#257 [BE-93] 지원서 합/불 관리자 페이지 조회
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/controller/ApplicantController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/dto/GetApplicantsStatusResponse.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/ApplicantService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/usecase/ApplicantQueryUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/interviewer/controller/InterviewerController.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/adaptor/AnswerAdaptor.java
Labels: feature✨

#259 [BE-94] 지원서 합/불 관리페이지 응답 오류 수정
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/dto/GetApplicantsStatusResponse.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/handler/ApplicantStateUpdateEventHandler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/ApplicantService.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/adaptor/AnswerAdaptor.java
Labels: bug-fix🚨, refactor♻️

#260 [BE-95] 면접 기록 조회 응답에 지원자의 합/불 상태를 나타내는 state 필드 추가
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/dto/RecordViewResponseDto.java
Labels: refactor♻️

#265 [BE-98] PASS_STATE_KEY 값 변경
  server/Recruit-Common/src/main/java/com/econovation/recruitcommon/consts/RecruitStatic.java
Labels: refactor♻️

#266 [BE-99] PASS_STATE_KEY 값 변경 복구
  server/Recruit-Common/src/main/java/com/econovation/recruitcommon/consts/RecruitStatic.java
Labels: refactor♻️

#268 [BE-100] 칸반보드 응답 INVISIBLE 타입 카드 포함
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/service/CardService.java
Labels: refactor♻️

#269 [PROD] 운영 서버에 반영
  .github/workflows/dev.yml
  server/Recruit-Api/build.gradle
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/aggregate/AnswerAggregate.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/aggregate/ApplicantStateUpdateEventListener.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/command/UpdateApplicantStateCommand.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/controller/ApplicantController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/dto/GetApplicantsStatusResponse.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/handler/ApplicantStateUpdateEventHandler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/AnswerCommandService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/ApplicantService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/state/config/ApplicantStateMachineConfig.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/state/support/ApplicantManager.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/state/support/PeriodCalculator.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/usecase/ApplicantCommandUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/usecase/ApplicantQueryUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/controller/BoardRestController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/handler/ApplicantCardCreateEventHandler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/service/CardService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/usecase/CardLoadUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/config/security/CorsConfig.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/config/security/SecurityConfig.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/config/security/ServletFilterConfiguration.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/interviewer/controller/InterviewerController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/controller/RecordController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/dto/RecordViewResponseDto.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/usecase/RecordUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/utils/ApplicantStateCheck.java
  server/Recruit-Api/src/main/resources/application.yml
  server/Recruit-Common/src/main/java/com/econovation/recruitcommon/consts/RecruitStatic.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/adaptor/AnswerAdaptor.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/MongoAnswer.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/ApplicantState.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/PassStates.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/PeriodStates.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/event/aggregateevent/ApplicantStateUpdateEvent.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/event/domainevent/ApplicantStateEvents.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/event/domainevent/ApplicantStateModifyEvent.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/exception/ApplicantErrorCode.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/exception/ApplicantWrongStateException.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/support/ApplicantStateManger.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/card/dto/BoardCardResponseDto.java
Labels: deployment

#274 [BE-97] 지원 현황 및 면접 기록 조회 API 정렬 로직 개선, 검색 쿼리 추가
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/aggregate/AnswerAggregate.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/aggregate/ApplicantStateUpdateEventListener.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/command/UpdateApplicantStateCommand.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/controller/ApplicantController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/dto/GetApplicantsStatusResponse.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/handler/ApplicantStateUpdateEventHandler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/AnswerCommandService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/ApplicantService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/state/config/ApplicantStateMachineConfig.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/state/support/ApplicantManager.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/state/support/PeriodCalculator.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/usecase/ApplicantQueryUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/controller/BoardRestController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/handler/ApplicantCardCreateEventHandler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/service/CardService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/interviewer/controller/InterviewerController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/interviewer/service/InterviewersService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/controller/RecordController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/dto/FilteredRecordsWithScoresDto.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/dto/RecordsViewResponseDto.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/usecase/RecordUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/utils/ApplicantStateCheck.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/utils/sort/SortHelper.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/utils/sort/strategy/AnswerObjectiveSortingStrategy.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/adaptor/AnswerAdaptor.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/MongoAnswer.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/ApplicantState.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/PassStates.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/PeriodStates.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/event/domainevent/ApplicantStateEvents.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/event/domainevent/ApplicantStateModifyEvent.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/exception/ApplicantErrorCode.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/exception/ApplicantWrongStateException.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/support/ApplicantStateManger.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/card/dto/BoardCardResponseDto.java
Labels: bug-fix🚨, feature✨

#277 release 4.0.1
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/aggregate/AnswerAggregate.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/aggregate/ApplicantStateUpdateEventListener.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/command/UpdateApplicantStateCommand.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/controller/ApplicantController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/dto/GetApplicantsStatusResponse.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/handler/ApplicantStateUpdateEventHandler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/AnswerCommandService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/ApplicantService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/state/config/ApplicantStateMachineConfig.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/state/support/ApplicantManager.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/state/support/PeriodCalculator.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/usecase/ApplicantQueryUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/controller/BoardRestController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/handler/ApplicantCardCreateEventHandler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/service/CardService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/interviewer/controller/InterviewerController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/interviewer/service/InterviewersService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/controller/RecordController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/dto/FilteredRecordsWithScoresDto.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/dto/RecordsViewResponseDto.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/usecase/RecordUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/utils/ApplicantStateCheck.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/utils/sort/SortHelper.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/utils/sort/strategy/AnswerObjectiveSortingStrategy.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/adaptor/AnswerAdaptor.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/MongoAnswer.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/ApplicantState.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/PassStates.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/PeriodStates.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/event/domainevent/ApplicantStateEvents.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/event/domainevent/ApplicantStateModifyEvent.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/exception/ApplicantErrorCode.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/exception/ApplicantWrongStateException.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/support/ApplicantStateManger.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/card/dto/BoardCardResponseDto.java
Labels: refactor♻️

#279 [BE-105] 지원 분야 정렬시 큰 카테고리부터 정렬되도록 수정
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/adaptor/AnswerAdaptor.java
Labels: bug-fix🚨

#280 release 4.0.2
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/adaptor/AnswerAdaptor.java
Labels: bug-fix🚨

#276 [BE-104] 최종 합격 발송 메일링(첨부파일 포함) 및 retry 반영
  portfolio.pdf
  server/Recruit-Api/src/main/java/com/econovation/recruit/RecruitApplication.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/ApplicantService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/usecase/ApplicantQueryUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email/handler/ApplicantRegisterEventConfirmEmailHandler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email/service/FinalEmailDiscussionEmailScheduler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email_template/controller/EmailTemplateController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email_template/docs/CreateEmailTemplateExceptionDocs.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email_template/dto/EmailTemplateRequestDto.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email_template/service/EmailTemplateService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email_template/usecase/EmailTemplateLoadUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email_template/usecase/EmailTemplateRegisterUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
  server/Recruit-Api/src/main/resources/application.yml
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/ApplicantState.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/adaptor/EmailTemplateAdaptor.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/domain/EmailTemplate.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/domain/EmailTemplateRepository.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/domain/EmailTemplateType.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/event/EmailSendEvent.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/exception/EmailTemplateErrorCode.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/exception/EmailTemplateInvaldFormatException.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/exception/EmailTemplateInvaldScheduleTimeException.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/exception/EmailTemplateNotFoundException.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/out/EmailTemplateLoadPort.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/out/EmailTemplateRecordPort.java
  server/Recruit-Infrastructure/build.gradle
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/apache/CommonsEmailSender.java
  server/Recruit-Infrastructure/src/main/resources/application-infrastructure.yml
  server/portfolio.pdf
Labels: feature✨

#284 [BE-106] attachment 존재 유무 로직 변경 및 portfolio 파일 이동
  portfolio.pdf
  server/Recruit-Api/Dockerfile
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email/service/FinalEmailDiscussionEmailScheduler.java
  server/Recruit-Api/src/main/resources/static/mail/portfolio.pdf
Labels: refactor♻️
