Repository JNU-econovation/econo-recruit, pull requests merged in 2025-03, with the labels that each got.

#299 [BE-112] CD 스크립트를 수정합니다.
  .github/workflows/deploy.yml
  .github/workflows/dev-deploy.yml
  .github/workflows/dev/dev-deploy.yml
  .github/workflows/dev/dev.yml
  .github/workflows/prod/deploy.yml
  .github/workflows/prod/prod.yml
Labels: refactor♻️

#300 [BE-112] 파일 경로 수정 및 메세지 수정
  .github/workflows/dev/dev-deploy.yml
  .github/workflows/dev/dev.yml
  .github/workflows/prod/deploy.yml
  .github/workflows/prod/prod.yml
Labels: refactor♻️

#302 [BE-112] github action 워크플로우 디렉터리 경로 수정
  .github/workflows/deploy.yml
  .github/workflows/dev-deploy.yml
  .github/workflows/dev.yml
  .github/workflows/prod.yml
Labels: refactor♻️

#303 [BE-112] ssh-action 변경
  .github/workflows/deploy.yml
  .github/workflows/dev-deploy.yml
Labels: refactor♻️

#304 refactor: secrets 값 변경
  .github/workflows/dev-deploy.yml
  .github/workflows/dev.yml
Labels: refactor♻️

#305 [BE-112] action-script 키 이름 변경
  .github/workflows/dev-deploy.yml
Labels: refactor♻️

#306 [BE-112] action script 에러 수정
  .github/workflows/dev.yml
Labels: refactor♻️

#307 [REFACTOR] github action ssh password 방식 적용
  .github/workflows/deploy.yml
  .github/workflows/dev-deploy.yml
  .github/workflows/dev.yml
  .github/workflows/prod.yml
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/config/security/CorsConfig.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email/service/FinalEmailDiscussionEmailScheduler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email_template/controller/EmailTemplateController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/record/service/RecordService.java
  server/Recruit-Api/src/main/resources/application.yml
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/ApplicantState.java
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/apache/CommonsEmailSender.java
Labels: refactor♻️

#308 [BE-112] 배포 자동화 셸 스크립트를 작성합니다.
  .github/workflows/deploy.yml
  .github/workflows/dev-deploy.yml
  .github/workflows/dev.yml
  .github/workflows/prod.yml
  .gitignore
  server/docker-compose.yml
  server/econo-recruie-start.sh
  server/proxy/nginx.conf
  server/redis/redis.config
Labels: refactor♻️

#309 [BE-112] 셸 스크립트 실행 권한 추가
  .github/workflows/deploy.yml
  .github/workflows/dev-deploy.yml
  .gitignore
Labels: refactor♻️

#310 [BE-112] 잘못된 파일 이름 수정
  .github/workflows/deploy.yml
  .github/workflows/dev-deploy.yml
  server/econo-recruit-start.sh
  server/redis/redis.conf
Labels: refactor♻️

#311 [BE-112] 디스코드 발송 에러 수정
  .github/workflows/deploy.yml
  .github/workflows/dev-deploy.yml
Labels: refactor♻️

#312 [BE-112] 디스코드 발송 스크립트 수정
  .github/workflows/deploy.yml
  .github/workflows/dev-deploy.yml
Labels: refactor♻️

#313 [BE-112] github action 디스코드 알림 전송 스크립트 수정
  .github/workflows/deploy.yml
  .github/workflows/dev-deploy.yml
Labels: refactor♻️

#314 [BE-112] 환경 변수를 설정하는 step 제거
  .github/workflows/deploy.yml
  .github/workflows/dev-deploy.yml
Labels: refactor♻️

#318 [BE-115] String으로 관리하던 html 폼을 분리하여 관리
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/apache/CommonsEmailSender.java
  server/Recruit-Infrastructure/src/main/resources/templates/email-form.html
Labels: refactor♻️

#273 [BE-96] 라벨 목록은 TF이상 권한인 면접관만 뜨도록 수정
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/interviewer/controller/InterviewerController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/interviewer/service/InterviewersService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/interviewer/usecase/InterviewerUseCase.java
Labels: feature✨

#324 [BE-119] PassStateToEnum 은 Response 에서 제외합니다.
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/controller/ApplicantController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/dto/ApplicantStateResponse.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/dto/GetApplicantsStatusResponse.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/state/ApplicantState.java
Labels: refactor♻️

#327 [BE-121] 지원서 backup 실패 오류를 해결합니다.
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/aggregate/AnswerCreatedEventListener.java
Labels: bug-fix🚨

#329 [BE-122] 지원자 상태별 이메일 템플릿 추가 및 Email 전송, 문자 발송 Service 구현
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/aggregate/AnswerAggregate.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/card/controller/BoardRestController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/config/SwaggerConfig.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email/controller/EmailController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email/handler/EmailSendEventHandler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email/service/ApplicantEmailService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email/service/FinalEmailDiscussionEmailScheduler.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email_template/service/EmailTemplateService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email_template/util/DefaultEmailProperties.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email_template/util/DefaultEmailTemplateGenerator.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/sms/helper/NcpSmsHelper.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/sms/helper/SmsMessageGenerator.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/sms/service/ApplicantSmsService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/user/helper/NcpMailHelper.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/utils/sort/SortHelper.java
  server/Recruit-Api/src/main/resources/application.yml
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/common/aop/redissonLock/RedissonLock.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/common/aop/redissonLock/RedissonLockAop.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/Applicant.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/domain/MongoAnswerAdaptor.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/dto/BlockRequestDto.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/domain/DefaultEmailTemplate.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/domain/EmailTemplate.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/domain/EmailTemplateType.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/event/EmailSendEvent.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/exception/EmailTemplateErrorCode.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/email_template/exception/EmailTemplateInvalidStateException.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/interviewer/domain/Role.java
  server/Recruit-Domain/src/main/resources/templates/email-final-failed.html
  server/Recruit-Domain/src/main/resources/templates/email-final-passed.html
  server/Recruit-Domain/src/main/resources/templates/email-first-failed.html
  server/Recruit-Domain/src/main/resources/templates/email-first-passed.html
  server/Recruit-Domain/src/main/resources/templates/email-register-confirm.html
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/apache/CommonsEmailSender.java
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/idp/client/IdpClient.java
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/ncp/NcpClient.java
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/ncp/NcpClients.java
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/ncp/NcpInfoErrorDecoder.java
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/ncp/NcpMailResponse.java
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/ncp/NcpProperties.java
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/ncp/NcpSmsDto.java
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/ncp/NcpSmsResponse.java
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/ses/AwsSesUtils.java
  server/Recruit-Infrastructure/src/main/java/com/econovation/recruitinfrastructure/ses/RawEmailAttachmentDto.java
  server/Recruit-Infrastructure/src/main/resources/application-infrastructure.yml
  server/econo-recruit-start.sh
Labels: feature✨

#330 [BE-122] 단일 지원자에게 메일을 발송합니다.
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/service/ApplicantService.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/applicant/usecase/ApplicantQueryUseCase.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/config/security/SecurityConfig.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email/controller/EmailController.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email/service/ApplicantEmailService.java
  server/Recruit-Domain/src/main/java/com/econovation/recruitdomain/domains/applicant/adaptor/AnswerAdaptor.java
  server/Recruit-Domain/src/main/resources/templates/email-final-failed.html
  server/Recruit-Domain/src/main/resources/templates/email-final-passed.html
  server/Recruit-Domain/src/main/resources/templates/email-first-failed.html
Labels: feature✨

#332 [BE-123] 메일 / 문자 내용을 최신화 합니다.
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email_template/util/DefaultEmailProperties.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/email_template/util/DefaultEmailTemplateGenerator.java
  server/Recruit-Api/src/main/java/com/econovation/recruit/api/sms/service/ApplicantSmsService.java
  server/Recruit-Api/src/main/resources/application.yml
  server/Recruit-Api/src/main/resources/static/mail/portfolio.pdf
  server/Recruit-Domain/src/main/resources/templates/email-final-failed.html
  server/Recruit-Domain/src/main/resources/templates/email-final-passed.html
  server/Recruit-Domain/src/main/resources/templates/email-first-failed.html
  server/portfolio.pdf
Labels: refactor♻️
